language: erlang

env:
  - LUA="luajit"

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

sudo: false
script: "busted spec"
